export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
export const BEGIN_PRODUCTS_DOWNLOAD = 'BEGIN_PRODUCTS_DOWNLOAD'
export const PRODUCTS_DOWNLOAD_OK = 'PRODUCTS_DOWNLOAD_OK'
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR'
export const RETRIEVE_PRODUCT_DELETE = 'RETRIEVE_PRODUCT_DELETE'
export const PRODUCT_DELETED_OK = 'PRODUCT_DELETED_OK'
export const PRODUCT_DELETED_ERROR = 'PRODUCT_DELETED_ERROR'

// los types son los que van definiendo lo que pasa en la aplicación